name: Update members

on:
  workflow_dispatch:
  schedule: 
    - cron:  '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout lf-landscape
        uses: actions/checkout@v4
        with:
          path: landscape
      - name: Checkout landscape-tools
        uses: actions/checkout@v4
        with:
          repository: jmertic/landscape-tools
          path: landscape-tools
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r landscape-tools/requirements.txt
      - name: Run build
        working-directory: ./landscape
        run: |
          ../landscape-tools/landscapemembers.py
          cp images/red-hat-inc.svg hosted_logos/red_hat_inc.svg
      - name: Save missing.csv file
        uses: actions/upload-artifact@v4
        with:
          name: missing-members 
          path: ./landscape/missing.csv
      - name: Checkout landscapeapp
        uses: actions/checkout@v4
        with:
          repository: cncf/landscapeapp
          path: landscapeapp
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Cleanup YAML files
        working-directory: ./landscapeapp
        run: |
          node tools/removePuppeteer
          npm install
          PROJECT_PATH=../landscape node tools/removeQuotes
          PROJECT_PATH=../landscape node tools/pruneExtraEntries
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          branch-suffix: timestamp
          path: ./landscape
          title: Daily update
          labels: daily-update
          commit-message: Daily update
      - name: Send missing.csv to specific users
        uses: dawidd6/action-send-mail@v3
        with:
          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          #
          # Format:
          #
          #  * smtp://user:password@server:port
          #  * smtp+starttls://user:password@server:port
          connection_url: ${{secrets.MAIL_CONNECTION}}
          # Required mail subject:
          subject: missing.csv from daily landscape build
          # Required recipients' addresses:
          to: memberops@linuxfoundation.org
          # Required sender full name (address can be skipped):
          from: LF Landscape
          # Optional plain body:
          body: See attached
          # Optional carbon copy recipients:
          cc: jmertic@linuxfoundation.org
          # Optional recipient of the email response:
          reply_to: jmertic@linuxfoundation.org
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: ./landscape/missing.csv
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low
          # Optional nodemailerlog: true/false
          nodemailerlog: false
          # Optional nodemailerdebug: true/false if true lognodem will also be set true
          nodemailerdebug: false
